stages:
- build
- test
- publish

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

slc6:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  script:
    - ci/fedora/packages.sh
    - yum install -y python-argparse tar
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-28:
  stage: build
  image: fedora:28
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-27:
  stage: build
  image: fedora:27
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

ubuntu-artful:
  stage: build
  image: ubuntu:artful
  script:
    - ci/debian/prepare.sh
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,ddeb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ci/debian/prepare.sh
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

cc7-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
  script:
    - yum install -y cc7/RPMS/*.rpm
    - davix-unit-tests

slc6-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  dependencies:
    - slc6
  script:
    - yum install -y slc6/RPMS/*.rpm
    - davix-unit-tests

fedora-27-test:
  stage: test
  image: fedora:28
  dependencies:
    - fedora-27
  script:
    - yum install -y fedora-27/RPMS/*.rpm
    - davix-unit-tests

#docs:
#  stage: publish
#  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
#  script:
#    - yum install -y git rpm-build python-argparse tar cmake python2-sphinx make sssd-client sudo python-pip
#    - rm -rf /usr/lib/python2.7/site-packages/chardet
#    - pip uninstall -y chardet
#    - pip install --upgrade sphinx
#    - packaging/make-docs.sh
#    - mv build/doc/build/html docs
#    - chown -R stci docs
#    - SNAPSHOT=$(date +%s)
#    - TARGET="/eos/project/d/davix/www/docs/${CI_COMMIT_REF_NAME}"
#    - STAGING_AREA="$TARGET-${SNAPSHOT}"
#    - sudo -u stci -H cp -r docs "$STAGING_AREA"
#    - sudo -u stci -H packaging/replace-directory.sh "$STAGING_AREA" "$TARGET"
#  tags:
#    - docker-cc7
#  retry: 2

rpms:
  stage: publish
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
    - slc6
  script:
    - yum install -y python sssd-client sudo createrepo
    - for platform in cc7 slc6; do sudo -u stci -H packaging/repo-manager.py --action add --base /eos/project/s/storage-ci/www/davix --ref ${CI_COMMIT_REF_NAME} --packages ${platform}/RPMS/* ${platform}/SRPMS/* ; done
    - sudo -u stci cp cc7/RPMS/* cc7/SRPMS/* /eos/project/d/dmc/www/repos/testing/el7/x86_64
    - sudo -u stci createrepo -q /eos/project/d/dmc/www/repos/testing/el7/x86_64
    - sudo -u stci cp slc6/RPMS/* slc6/SRPMS/* /eos/project/d/dmc/www/repos/testing/el6/x86_64
    - sudo -u stci createrepo -q /eos/project/d/dmc/www/repos/testing/el6/x86_64
  tags:
    - docker-cc7
  retry: 2
