stages:
- build
- test
- publish

cmake-no-git:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build gcc-c++
    - git submodule update --init --recursive
    - ./packaging/make-srpm.sh
    - yum-builddep -y build/SRPMS/*
    - rm -rf .git build
    - mkdir build
    - cd build
    - cmake3 ..

cmake-tarball:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build gcc-c++
    - git submodule update --init --recursive
    - ./packaging/make-srpm.sh
    - yum-builddep -y build/SRPMS/*
    - packaging/make-dist.sh
    - cd build
    - tar xf davix-*.tar.gz
    - cd davix-*/
    - mkdir build && cd build
    - cmake3 ..

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

centos8:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  script:
    - ci/fedora/packages.sh
    - yum install -y git rpm-build
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-33:
  stage: build
  image: fedora:33
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-34:
  stage: build
  image: fedora:34
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-rawhide:
  stage: build
  image: fedora:rawhide
  script:
    - ci/fedora/packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  allow_failure: true
  artifacts:
    paths:
      - "$CI_JOB_NAME"

ubuntu-focal:
  stage: build
  image: ubuntu:focal
  script:
    - ci/debian/packages.sh
    - apt install -y python2
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,ddeb,dsc} ${CI_JOB_NAME}
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  artifacts:
    paths:
    - "$CI_JOB_NAME"

debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ci/debian/packages.sh
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

docs-generate:
  stage: build
  image: fedora:34
  script:
    - dnf install -y git python3-sphinx python3-pip gcc-c++ rpm-build dnf-plugins-core python2 python3-breathe make
    - packaging/make-docs.sh
    - mv build/doc/build/html docs
  artifacts:
    paths:
    - docs

cc7-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
  script:
    - yum install -y cc7/RPMS/*.rpm
    - davix-unit-tests

centos8-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  dependencies:
    - centos8
  script:
    - dnf install -y epel-release
    - dnf install -y centos8/RPMS/*.rpm
    - davix-unit-tests

fedora-33-test:
  stage: test
  image: fedora:33
  dependencies:
    - fedora-33
  script:
    - dnf install -y fedora-33/RPMS/*.rpm
    - davix-unit-tests

fedora-34-test:
  stage: test
  image: fedora:34
  dependencies:
    - fedora-34
  script:
    - dnf install -y fedora-34/RPMS/*.rpm
    - davix-unit-tests

docs:
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  dependencies:
    - docs-generate
  script:
    - yum install -y sssd-client sudo
    - automount
    - cat "$DAVIXCI_PW" | kinit davixci
    - eosfusebind
    - SNAPSHOT=$(date +%s)
    - TARGET="/eos/project/d/davix/www/docs/${CI_COMMIT_REF_NAME}"
    - STAGING_AREA="$TARGET-${SNAPSHOT}"
    - cp -r docs "$STAGING_AREA"
    - ci/replace-directory.sh "$STAGING_AREA" "$TARGET"
    - sleep 60
  tags:
    - docker-privileged
  retry: 2
  only:
    - branches@dmc/davix
    - tags@dmc/davix

rpms:
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  dependencies:
    - cc7
    - centos8
  script:
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$STCI_PASSWORD" | kinit stci
    - eosfusebind
    - for platform in cc7 centos8; do packaging/repo-manager.py --action add --base /eos/project/s/storage-ci/www/davix --ref ${CI_COMMIT_REF_NAME} --packages ${platform}/RPMS/* ${platform}/SRPMS/* ; done
    - sleep 60
  tags:
    - docker-privileged
  retry: 2
  only:
    - branches@dmc/davix
    - tags@dmc/davix

rpms-dmc:
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  dependencies:
    - cc7
    - centos8
    - fedora-33
    - fedora-34
    - fedora-rawhide
  script:
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$STCI_PASSWORD" | kinit stci
    - eosfusebind
    - declare -A DISTMAP=( [cc7]=el7 [centos8]=el8 [fedora-33]=fc33 [fedora-34]=fc34 [fedora-rawhide]=fc-rawhide )
    - |
        for platform in cc7 centos8 fedora-33 fedora-34 fedora-rawhide ; do
          dist=${DISTMAP[${platform}]};
          cp -n ${platform}/RPMS/* ${platform}/SRPMS/* /eos/project-d/dmc/www/repos/testing/${dist}/x86_64 || true;
          packaging/update-repo.sh /eos/project-d/dmc/www/repos/testing/${dist}/x86_64;
        done
    - sleep 30
  tags:
    - docker-privileged
  retry: 2
  only:
    - master@dmc/davix
    - devel@dmc/davix
